name: Deploy to TarkovTrackerNext on next push
"on":
  push:
    branches:
      - next
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Next
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TARKOVTRACKER_NEXT }}"
          channelId: live
          projectId: tarkovtracker-next
